(function() {var implementors = {};
implementors["supercow"] = ["impl&lt;A:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>,&nbsp;B:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='supercow/ext/struct.InlineStorage.html' title='supercow::ext::InlineStorage'>InlineStorage</a>&lt;A,&nbsp;B&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='supercow/ext/struct.BoxedStorage.html' title='supercow::ext::BoxedStorage'>BoxedStorage</a>","impl&lt;'a,&nbsp;OWNED,&nbsp;BORROWED:&nbsp;?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>,&nbsp;SHARED,&nbsp;STORAGE&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='supercow/struct.Supercow.html' title='supercow::Supercow'>Supercow</a>&lt;'a,&nbsp;OWNED,&nbsp;BORROWED,&nbsp;SHARED,&nbsp;STORAGE,&nbsp;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.tuple.html'>()</a>&gt; <span class='where'>where BORROWED: 'a, <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const BORROWED</a>: <a class='trait' href='supercow/ext/trait.PointerFirstRef.html' title='supercow::ext::PointerFirstRef'>PointerFirstRef</a>, STORAGE: <a class='trait' href='supercow/ext/trait.OwnedStorage.html' title='supercow::ext::OwnedStorage'>OwnedStorage</a>&lt;OWNED,&nbsp;SHARED&gt;</span>","impl&lt;'a,&nbsp;OWNED,&nbsp;BORROWED:&nbsp;?<a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html' title='core::marker::Sized'>Sized</a>,&nbsp;SHARED,&nbsp;STORAGE&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='supercow/struct.Supercow.html' title='supercow::Supercow'>Supercow</a>&lt;'a,&nbsp;OWNED,&nbsp;BORROWED,&nbsp;SHARED,&nbsp;STORAGE,&nbsp;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const BORROWED</a>&gt; <span class='where'>where BORROWED: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> + 'a, <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const BORROWED</a>: <a class='trait' href='supercow/ext/trait.PointerFirstRef.html' title='supercow::ext::PointerFirstRef'>PointerFirstRef</a>, STORAGE: <a class='trait' href='supercow/ext/trait.OwnedStorage.html' title='supercow::ext::OwnedStorage'>OwnedStorage</a>&lt;OWNED,&nbsp;SHARED&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
